### PR TITLE
Fix locale switch on Android

### LINKED ISSUE #203: Locale switch
It would be nice to have locale switch. My system locale is English, but I would like to use the app in Ukrainian localization

### PR DESCRIPTION
**Pull request by zhuiks**
This fixes #203

It also introduces unit tests

### CODE REVIEW

**Comment by zhuiks** [comment]
I have two issues:
1. I have trouble starting it on Android Emulator. Sometimes it starts. Some errors from #344 are always present. 
2.  I can't figure out why jest is not able to run with Github Actions

@tobias-klein would you mind to take a look

**Comment by zhuiks** [comment]
> 2. I can't figure out why jest is not able to run with Github Actions

I figure out the second issue. I chose to use [`jest-electron`](https://github.com/hustcc/jest-electron) for unit tests as it allows tests to run in a browser environment. That will be important when writing unit tests for stand-alone web components (I already implemented one under PR #317 [`assistant_checkbox.spec.js`](https://github.com/ezra-project/ezra-project/blob/6cfbc364120112e1094d351bb7287be93ee6937c/app/frontend/components/module_assistant/__tests__/assistant_checkbox.spec.js).

Anyway `jest-electron` works with Github Actions on macOs image according to their readme. From what I understood, there is no limit for public repositories. But let me know if it's an issue.

File: app/frontend/helpers/i18n_helper.js [hunk 1]
```diff
@@ -67,21 +68,15 @@ module.exports.getLocalizedDate = function(timestamp) {
   return new Date(Date.parse(timestamp)).toLocaleDateString(locale);
 }
 
-function toTitleCase(str) {
-  return str.slice(0, 1).toLocaleUpperCase() + str.slice(1);
-}
-
 module.exports.getLanguageName = function(code, includeNativeName = false, currentLocale = null) {
```
Comment (tobias-klein) [inline app/frontend/helpers/i18n_helper.js:71]: How about adding some JSDoc comments for this function, since it seems a bit involved.

File: app/lib/language_mapper.js [hunk 2]
```diff
@@ -16,96 +16,126 @@
...
   }
+  mappingExistsCache[languageCode][localeCode] = languageName;
 
-  mappingExists(languageCode) {
-    if (languageCode in this.mappingExistsCache) {
+  return languageName;
+};
 
-      return this.mappingExistsCache[languageCode];
+module.exports.getLanguageDetails = function (languageCode, localeCode = 'en') {
```
Comment (tobias-klein) [inline app/lib/language_mapper.js:39]: I suggest to add JSDoc comments - from the outset it's not super clear what this function returns.

**Review by tobias-klein — COMMENTED** [review]
This is just a quick feedback for now. I'll have another look later.

File: app/frontend/helpers/ezra_helper.js [hunk 3]
```diff
@@ -18,8 +18,8 @@
 
 
 /**
- * This module contains utility functions that are used througt the app
- * @module ezra_helper
+ * This module contains utility functions that are used through the app
+ * @module ezraHelper
```
Comment (zhuiks) [inline app/frontend/helpers/ezra_helper.js:22]: I think using camelCase instead of under_line is more appropriate as in code we would use camelCase (i.e. ezdraHelper.waitUntilIdle())

File: app/lib/language_mapper.js [hunk 4]
```diff
@@ -16,96 +16,161 @@
...
+ * @property {(string|undefined)} iso6393 ISO 693-3 3-letter language code
+ * @property {(string|undefined)} iso6392B ISO 693-2/B 3-letter language code
+ * @property {(string|undefined)} iso6392T ISO 693-2/T 3-letter language code
+ * @property {(string|undefined)} iso6391 ISO 693-1 2-letter language code
+ */
+/**
+ * Function to get various language details
+ * @param {string} languageCode Language identifier is a combination of sub-tags (Language[-Script][-Region]) for Language and optionally Script, and/or Region, according to BCP 47 and RFC 4647
+ * @param {string} [localeCode='en'] Locale/Language code to localize language information into
+ * @returns {LanguageDetails} details Language details
```
Comment (zhuiks) [inline app/lib/language_mapper.js:69]: I'm not sure if @typedef will look nice for return annotation under JSDoc-generated documentation, but it is picked up nicely by VSCode

**Comment by tobias-klein** [comment]
I am getting these errors - why is language_mapper.spec.js even included in the code?

```

06-14 22:25:33.407 22514 22611 E NODEJS-CORDOVA: Node assets copy failed: java.io.FileNotFoundException: www/nodejs-project/app/lib/__tests__/language_mapper.spec.js
06-14 22:25:33.408 22514 22611 W System.err: java.io.FileNotFoundException: www/nodejs-project/app/lib/__tests__/language_mapper.spec.js
06-14 22:25:33.409 22514 22611 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.copyAssetFile(NodeJS.java:496)
06-14 22:25:33.409 22514 22611 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.copyNodeJSAssets(NodeJS.java:443)
06-14 22:25:33.409 22514 22611 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.access$100(NodeJS.java:30)
06-14 22:25:33.409 22514 22611 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS$1.run(NodeJS.java:114)
06-14 22:25:33.941 22514 22514 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 16658 : Starting up nodejs engine!
06-14 22:25:33.941 22514 22514 I chromium: [INFO:CONSOLE(16658)] "Starting up nodejs engine!", source: file:///android_asset/www/dist/ezra_init.js (16658)
06-14 22:27:13.036 23368 23467 E NODEJS-CORDOVA: Node assets copy failed: java.io.FileNotFoundException: www/nodejs-project/app/lib/__tests__/language_mapper.spec.js
06-14 22:27:13.037 23368 23467 W System.err: java.io.FileNotFoundException: www/nodejs-project/app/lib/__tests__/language_mapper.spec.js
06-14 22:27:13.037 23368 23467 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.copyAssetFile(NodeJS.java:496)
06-14 22:27:13.038 23368 23467 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.copyNodeJSAssets(NodeJS.java:443)
06-14 22:27:13.038 23368 23467 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS.access$100(NodeJS.java:30)
06-14 22:27:13.038 23368 23467 W System.err:    at com.janeasystems.cdvnodejsmobile.NodeJS$1.run(NodeJS.java:114)
06-14 22:27:13.597 23368 23368 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 16658 : Starting up nodejs engine!
06-14 22:27:13.597 23368 23368 I chromium: [INFO:CONSOLE(16658)] "Starting up nodejs engine!", source: file:///android_asset/www/dist/ezra_init.js (16658)
```

**Comment by zhuiks** [comment]
Ok, I see the same error in logcat
` www/nodejs-project/app/lib` is symlink to `ezra-bible-app/app/lib` which right now has a test folder

**Comment by zhuiks** [comment]
I created links to files instead of entire `lib` folder
https://github.com/ezra-bible-app/ezra-bible-app-cordova/pull/15
Right now it runs for me on emulator, although I'm still getting those #344 errors
@tobias-klein Please check

**Comment by tobias-klein** [comment]
I am getting these errors on startup (extracted from adb logcat).

```
06-15 20:19:22.080  4766  4766 D SystemWebChromeClient: file:///android_asset/www/dist/ezra_init.js: Line 16707 : nodejs: main.js loaded / data dir: /data/user/0/net.ezrabibleapp.cordova/files
06-15 20:19:22.080  4766  4766 I chromium: [INFO:CONSOLE(16707)] "nodejs: main.js loaded / data dir: /data/user/0/net.ezrabibleapp.cordova/files", source: file:///android_asset/www/dist/ezra_init.js (16707)
06-15 20:19:22.080  4766  4939 E NODEJS-MOBILE: [INFO:CONSOLE(16707)] "nodejs: main.js loaded / data dir: /data/user/0/net.ezrabibleapp.cordova/files", source: file:///android_asset/www/dist/ezra_init.js (16707)
06-15 20:19:24.315  4766  4766 W Thread-5: type=1400 audit(0.0:9473): avc: granted { execute } for path="/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/node_modules/sqlite3/lib/binding/node_abi-platform-arch/node_sqlite3.node" dev="dm-2" ino=1000774 scontext=u:r:untrusted_app:s0:c97,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c97,c257,c512,c768 tclass=file
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at Object.<anonymous> (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/lib/language_mapper.js:26:30)
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at Object.<anonymous> (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/database/models/bibletranslation.js:25:24)
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at /data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/database/models/index.js:59:19
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at module.exports (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/database/models/index.js:58:6)
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at IpcDbHandler.initDatabase (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc_db_handler.js:53:50)
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at async IPC.initDatabase (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/backend/ipc/ipc.js:85:5)
06-15 20:19:24.732  4766  4939 E NODEJS-MOBILE: (node:4766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

It seems like this is coming from here:
`
06-15 20:19:24.731  4766  4939 E NODEJS-MOBILE:     at Object.<anonymous> (/data/data/net.ezrabibleapp.cordova/files/www/nodejs-project/app/lib/language_mapper.js:26:30)`

It seems like this line produces an exception in nodejs-mobile.

`const hasIntlDisplayNames = Intl && typeof Intl === "object" && typeof Intl.DisplayNames === "function";`

**Comment by zhuiks** [comment]
@tobias-klein Thanks for pointing out that error. I moved that line inside the function as it suppose to be called in browser context.
Now I don't get any errors!

**Comment by tobias-klein** [comment]
This settles it! The locale selection menu is looking fine on Android now!

**Review by tobias-klein — APPROVED** [review]
